# -*- mode: dockerfile; -*-
# vim: ft=dockerfile

FROM rust
WORKDIR /usr/src

RUN apt-get update && \
    apt-get dist-upgrade -y

RUN USER=root cargo new gateway
WORKDIR /usr/src/gateway
COPY Cargo.toml Cargo.lock ./
COPY gateway ./gateway
COPY macros ./macros
RUN cargo install --path gateway
